dtbo-$(CONFIG_ARCH_SUN) += ../../qcom/display/display/sun-sde.dtbo \
		display/sun-sde-display-ayn-odin3-overlay.dtbo

always-y    := $(dtb-y) $(dtbo-y)
subdir-y    := $(dts-dirs)
clean-files    := *.dtb *.dtbo
